name: brainbash_frontend
description: "BrainBash - Cognitive Assessment App"
publish_to: 'none'
version: 0.1.0+3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  shared_preferences: ^2.3.4
  google_sign_in: ^6.2.2
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
